# Matrix Operation 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import sparse

# https://learning.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html#

# Creating a Matrix
To create a matrix we can use a NumPy two-dimensional array. In our solution, the matrix contains three rows and two columns (a column of 1s and a column of 2s).

**Pros and Cons:** the matrix data structure is not recommended for two reasons. First, arrays are the de facto standard data structure of NumPy. Second, the vast majority of NumPy operations return arrays, not matrix objects

In [2]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [3]:
matrix = np.array([[1, 2, 3, 1],
                   [2, 4, 6, 1],
                   [3, 8, 9, 1],
                   [10,11,12,1]])
matrix

array([[ 1,  2,  3,  1],
       [ 2,  4,  6,  1],
       [ 3,  8,  9,  1],
       [10, 11, 12,  1]])

# Describing Matrix

In [4]:
# View number of rows and columns
print(matrix.shape)

# View number of elements (rows * columns)
print(matrix.size)

# View number of dimensions
print(matrix.ndim)

(4, 4)
16
2


# Determinant

In [5]:
print(matrix)

# Determi# Return determinant of matrix
np.linalg.det(matrix)

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]


36.0

# Diagonal Elements

In [5]:
print(matrix)

# Return diagonal elements
matrix.diagonal()

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]


array([1, 4, 9, 1])

NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also possible to get a diagonal off from the main diagonal by using the offset parameter:

In [6]:
print(matrix)

# Return diagonal one above the main diagonal
print(matrix.diagonal(offset=1))

# Return diagonal one below the main diagonal
print(matrix.diagonal(offset=-1))

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]
[2 6 1]
[ 2  8 12]


In [6]:
# Another Way
np.diag(matrix)

array([1, 4, 9, 1])

# Create a Diagonal Matrix

In [14]:
diagonal_mat1 = np.diag([1,1,1])
diagonal_mat2 = np.diag([1,2,3])

# Some Other Operation with Diagonal Matrix

In [17]:
# Both Produce the same result
np.inner(diagonal_mat1, diagonal_mat2)
diagonal_mat1.dot(diagonal_mat2)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
np.outer(diagonal_mat1, diagonal_mat2)

array([[1, 0, 0, 0, 2, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 2, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 2, 0, 0, 0, 3]])

# Trace of matrix
The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods. Given a NumPy multidimensional array, we can calculate the trace using trace. We can also return the diagonal of a matrix and calculate its sum.

In [18]:
print(matrix)
# Return trace
print(matrix.trace())

# Return diagonal and sum elements
sum(matrix.diagonal())

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]
15


15

# Transposing a Vector or Matrix
Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. One nuanced point that is typically overlooked outside of a linear algebra class is that, technically, a vector cannot be transposed because it is just a collection of values

In [8]:
print(matrix.T)

vector = np.array([1, 2, 3, 4, 5, 6]).T   # no change
print(vector)

vector = np.array([[1, 2, 3, 4, 5, 6]]).T
print(vector)

[[ 1  2  3 10]
 [ 2  4  8 11]
 [ 3  6  9 12]
 [ 1  1  1  1]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Rank of a Matrix


In [9]:
print(matrix)

# Return matrix rank
np.linalg.matrix_rank(matrix)

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]


4

# Eigenvalues and Eigenvectors

In [10]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("eigenvalues: ",eigenvalues)
print(eigenvectors)

eigenvalues:  [16.69813223  1.37262985 -2.42236393 -0.64839816]
[[-0.19136692 -0.33786015  0.27061639  0.13964786]
 [-0.33730665 -0.01927195  0.15062268 -0.61113392]
 [-0.52364691  0.27123591 -0.0937311   0.52314184]
 [-0.75854917 -0.90106059 -0.9461998  -0.57735295]]


Eigenvectors are widely used in machine learning libraries. Intuitively, given a linear transformation represented by a matrix, A, eigenvectors are vectors that, when that transformation is applied, change only in scale (not direction). More formally: **Av=λv**

where A is a square matrix, λ contains the eigenvalues and v contains the eigenvectors. In NumPy’s linear algebra toolset, eig lets us calculate the eigenvalues, and eigenvectors of any square matrix.

# Calculating Dot Products

In [11]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])


# Calculate dot product
np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

 # Adding and Subtracting Matrices

In [12]:
# Add two matrices
print(np.add(matrix_a, matrix_b))

print(matrix_a + matrix_b)

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]


In [13]:
# Subtract two matrices
print(np.subtract(matrix_a, matrix_b))

print(matrix_a - matrix_b)

[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


# Inverting a Matrix
The inverse of a square matrix, A, is a second matrix $A^{-1}$, such that: 

${AA}^{-1} = I$

where $I$ is the identity matrix. In NumPy we can use linalg.inv to calculate $A^{-1}$ if it exists. To see this in action, we can multiply a matrix by its inverse and the result is the identity matrix:

In [14]:
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[ 8.33333333e-02,  0.00000000e+00, -2.50000000e-01,
         1.66666667e-01],
       [ 5.00000000e-01, -1.00000000e+00,  5.00000000e-01,
        -2.36217665e-17],
       [-6.94444444e-01,  1.00000000e+00, -2.50000000e-01,
        -5.55555556e-02],
       [ 2.00000000e+00, -1.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

## Creating a Sparse Matrix

**Sparse matrices** only store nonzero elements and assume all other values will be zero, leading to significant computational savings. Here, we created a NumPy array with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix we can see that only the nonzero values are stored.

There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively. For example, the element 1 is in the second row and second column. We can see the advantage of sparse matrices if we create a much larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:

In [15]:
from scipy import sparse

matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

# final sparse matrix
print(matrix_sparse)
print('############ For Large Matrix ##############')

# another example
# Create larger matrix
matrix_large = np.array([[0, 0, 3, 0, 0, 0, 0, 0, 4, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 4, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
############ For Large Matrix ##############
  (0, 2)	3
  (0, 8)	4
  (1, 1)	1
  (1, 8)	4
  (2, 0)	3


In [ ]:
# Matrix Multiplications