# Matrix Operation 

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import sparse

# https://learning.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html#

In [27]:
matrix = np.array([[1, 2, 3, 1],
                   [2, 4, 6, 1],
                   [3, 8, 9, 1],
                   [10,11,12,1]])
matrix

array([[ 1,  2,  3,  1],
       [ 2,  4,  6,  1],
       [ 3,  8,  9,  1],
       [10, 11, 12,  1]])

# Determinant

In [28]:
print(matrix)

# Determi# Return determinant of matrix
np.linalg.det(matrix)

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]


36.0

# Diagonal Elements

In [29]:
print(matrix)

# Return diagonal elements
matrix.diagonal()

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]


array([1, 4, 9, 1])

NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also possible to get a diagonal off from the main diagonal by using the offset parameter:

In [30]:
print(matrix)

# Return diagonal one above the main diagonal
print(matrix.diagonal(offset=1))

# Return diagonal one below the main diagonal
print(matrix.diagonal(offset=-1))

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]
[2 6 1]
[ 2  8 12]


# Trace of matrix
The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods. Given a NumPy multidimensional array, we can calculate the trace using trace. We can also return the diagonal of a matrix and calculate its sum.

In [31]:
# Return trace
print(matrix.trace())

# Return diagonal and sum elements
sum(matrix.diagonal())

15


15

# Transposing a Vector or Matrix
Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. One nuanced point that is typically overlooked outside of a linear algebra class is that, technically, a vector cannot be transposed because it is just a collection of values

In [32]:
print(matrix.T)

vector = np.array([1, 2, 3, 4, 5, 6]).T   # no change
print(vector)

vector = np.array([[1, 2, 3, 4, 5, 6]]).T
print(vector)

[[ 1  2  3 10]
 [ 2  4  8 11]
 [ 3  6  9 12]
 [ 1  1  1  1]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Rank of a Matrix


In [34]:
print(matrix)

# Return matrix rank
np.linalg.matrix_rank(matrix)

[[ 1  2  3  1]
 [ 2  4  6  1]
 [ 3  8  9  1]
 [10 11 12  1]]


4

# Eigenvalues and Eigenvectors

In [37]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("eigenvalues: ",eigenvalues)
print(eigenvectors)

eigenvalues:  [16.69813223  1.37262985 -2.42236393 -0.64839816]
[[-0.19136692 -0.33786015  0.27061639  0.13964786]
 [-0.33730665 -0.01927195  0.15062268 -0.61113392]
 [-0.52364691  0.27123591 -0.0937311   0.52314184]
 [-0.75854917 -0.90106059 -0.9461998  -0.57735295]]


Eigenvectors are widely used in machine learning libraries. Intuitively, given a linear transformation represented by a matrix, A, eigenvectors are vectors that, when that transformation is applied, change only in scale (not direction). More formally: **Av=λv**

where A is a square matrix, λ contains the eigenvalues and v contains the eigenvectors. In NumPy’s linear algebra toolset, eig lets us calculate the eigenvalues, and eigenvectors of any square matrix.

# Calculating Dot Products

In [42]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])


# Calculate dot product
np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

 # Adding and Subtracting Matrices

In [43]:
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [44]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])