# Numpy Operations

NumPy is the foundation of the Python machine learning stack. NumPy allows for efficient operations on the data structures often used in machine learning: vectors, matrices, and tensors. 

For More visit  **[This Link](https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html)**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse

## Creating a Vector
NumPy’s main data structure is the multidimensional array. To create a vector, we simply create a one-dimensional array. Just like vectors, these arrays can be represented horizontally (i.e., rows) or vertically (i.e., columns).

In [3]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])
print(vector_row)

# Create a vector as a column
vector_column = np.array([[1],[2],[3]])
print(vector_column)


[1 2 3]
[[1]
 [2]
 [3]]


# Some Basic Operation

In [15]:
array = np.array([1,2,3])
print(array)

# Sqrt
print(np.sqrt(array))

# Exponential
print(np.exp(array))

# log
print(np.log(array))

[1 2 3]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


## Creating a Matrix
To create a matrix we can use a NumPy two-dimensional array. In our solution, the matrix contains three rows and two columns (a column of 1s and a column of 2s).

**Pros and Cons:** the matrix data structure is not recommended for two reasons. First, arrays are the de facto standard data structure of NumPy. Second, the vast majority of NumPy operations return arrays, not matrix objects

In [4]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

In [5]:
from scipy import sparse

matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

# final sparse matrix
print(matrix_sparse)
print('############ For Large Matrix ##############')

# another example
# Create larger matrix
matrix_large = np.array([[0, 0, 3, 0, 0, 0, 0, 0, 4, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 4, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
############ For Large Matrix ##############
  (0, 2)	3
  (0, 8)	4
  (1, 1)	1
  (1, 8)	4
  (2, 0)	3


## Selecting Elements
Like most things in Python, NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1.

In [6]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)

# Select second row, second column
print("second row, second column:",matrix[1,1])

# Select the first two rows and all columns of a matrix
print("first two rows and all columns")
print(matrix[:2,:])

# Select all rows and the second column
print("all rows and the second column")
print(matrix[:,1:2])

# select 1st row
print(matrix[:1,:])

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
second row, second column: 5
first two rows and all columns
[[1 2 3]
 [4 5 6]]
all rows and the second column
[[2]
 [5]
 [8]]
[[1 2 3]]


## Describing a Matrix

In [7]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# View number of rows and columns
print(matrix.shape)

# View number of elements (rows * columns)
print(matrix.size)

# View number of dimensions
print(matrix.ndim)

(3, 4)
12
2


## Creating a Sparse Matrix

**Sparse matrices** only store nonzero elements and assume all other values will be zero, leading to significant computational savings. Here, we created a NumPy array with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix we can see that only the nonzero values are stored.

There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively. For example, the element 1 is in the second row and second column. We can see the advantage of sparse matrices if we create a much larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:

In [8]:
from scipy import sparse

matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

# final sparse matrix
print(matrix_sparse)
print('############ For Large Matrix ##############')

# another example
# Create larger matrix
matrix_large = np.array([[0, 0, 3, 0, 0, 0, 0, 0, 4, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 4, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
############ For Large Matrix ##############
  (0, 2)	3
  (0, 8)	4
  (1, 1)	1
  (1, 8)	4
  (2, 0)	3
