# Numpy Operations

NumPy is the foundation of the Python machine learning stack. NumPy allows for efficient operations on the data structures often used in machine learning: vectors, matrices, and tensors. 

For More visit  **[This Link](https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html)**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse

## Creating a Vector
NumPy’s main data structure is the multidimensional array. To create a vector, we simply create a one-dimensional array. Just like vectors, these arrays can be represented horizontally (i.e., rows) or vertically (i.e., columns).

In [3]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])
print(vector_row)

# Create a vector as a column
vector_column = np.array([[1],[2],[3]])
print(vector_column)


[1 2 3]
[[1]
 [2]
 [3]]


# Some Basic Operation

In [4]:
array = np.array([1,2,3])
print(array)

# Sqrt
print(np.sqrt(array))

# Exponential
print(np.exp(array))

# log
print(np.log(array))

[1 2 3]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


# Creating Matrix All Zeros/Ones

In [5]:
# One Dimensions
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
# Two Dimensions
print(np.zeros((10,10)))
print("#################################")
print(np.ones((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
#################################
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Generating Matrix Using Random Values

In [9]:
np.random.random((10,10)) # all number is 0 to 1

array([[0.5916155 , 0.95571676, 0.70530916, 0.65821412, 0.8690935 ,
        0.35191167, 0.39173523, 0.98756039, 0.82828283, 0.88275095],
       [0.07852894, 0.59972686, 0.98004468, 0.70730418, 0.02510837,
        0.23489174, 0.53594036, 0.8401295 , 0.77942969, 0.11617305],
       [0.56801146, 0.7136892 , 0.97596673, 0.27379473, 0.74925483,
        0.7953665 , 0.5191404 , 0.29080202, 0.3704398 , 0.19542537],
       [0.87817346, 0.43322324, 0.27251073, 0.39024101, 0.23138266,
        0.44918918, 0.97217284, 0.86247112, 0.11348359, 0.15806844],
       [0.0597532 , 0.13340815, 0.45037348, 0.72278489, 0.15405554,
        0.80121431, 0.47989677, 0.09007153, 0.86003635, 0.32357882],
       [0.21632864, 0.4375126 , 0.36945612, 0.25179009, 0.14547943,
        0.64960902, 0.27643195, 0.62374276, 0.5566481 , 0.78444994],
       [0.06141527, 0.40080275, 0.85529676, 0.80786271, 0.91471545,
        0.18260224, 0.42489816, 0.35586263, 0.91696579, 0.10142722],
       [0.07553554, 0.59326757, 0.2897768

In [11]:
rand_mat = np.random.randn(10,10)
rand_mat

array([[-0.94486236,  0.59265917, -0.38521191,  0.83705557, -0.79572066,
         0.94082635,  0.45754372,  0.09645949, -0.21139527,  1.3299987 ],
       [ 0.3489898 , -1.09943   ,  0.82932353, -0.3803665 ,  2.17561481,
        -0.20592407,  0.25564086, -0.14545028, -0.03189815,  1.09556617],
       [ 1.91298074,  2.04876069,  0.75528838, -0.32544716,  1.9610424 ,
        -0.38385554, -0.48784983,  0.70880354, -1.19573297,  0.35143598],
       [-0.61868117, -0.93542684, -0.33359439,  0.11858185,  0.06868442,
        -0.06700009, -0.41409563,  0.29136017,  0.7410052 ,  0.38095526],
       [ 1.17422027, -1.10891857,  0.90209236,  0.64335334,  0.08336877,
        -0.59795566, -1.05028122, -0.74571266,  1.90920316,  0.7449941 ],
       [-0.60172442, -2.52059802, -0.51963278, -0.09312394, -0.16731676,
         0.53876368,  1.048235  , -0.03428124, -0.3023789 ,  0.27896099],
       [-2.08004404,  0.13108102, -0.08191773, -2.06474833,  0.69504781,
         0.8807927 ,  1.34284963, -0.99129152

# Statistics of the matrix

In [12]:
rand_mat.mean()  # mean

0.08067251108594782

In [13]:
rand_mat.var() # variance

1.0083604529754069

In [15]:
rand_mat.std()  # standard daviation

1.004171525674477

## Selecting Elements
Like most things in Python, NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1.

In [51]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)

# Select second row, second column
print("second row, second column:",matrix[1,1])

# Select the first two rows and all columns of a matrix
print("first two rows and all columns")
print(matrix[:2,:])

# Select all rows and the second column
print("all rows and the second column")
print(matrix[:,1:2])

# select 1st row
print(matrix[:1,:])

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
second row, second column: 5
first two rows and all columns
[[1 2 3]
 [4 5 6]]
all rows and the second column
[[2]
 [5]
 [8]]
[[1 2 3]]


# Dot Product

In [52]:
A = np.array([1,2])

B = np.array([2,1])

# Find Magnitude Manual Operation
dot = 0
for ai, bi in zip(A,B):
    dot += ai*bi
print("manual: ",dot)

# Automatic Operation
print("auto: ",np.sum(A*B))
print("auto: ",(A*B).sum()) #Similar
print("auto: ",np.dot(A,B)) # similar
print("auto: ", A.dot(B))
print("auto: ", B.dot(A))

# Dot Product
print(A*B)
A_magnitude = np.linalg.norm(A)
B_magnitude = np.linalg.norm(B)
print(A_magnitude, B_magnitude)

# Angel
cosangle = A.dot(B)/(A_magnitude*B_magnitude)
angel = np.arccos(cosangle)
print(angel)


manual:  4
auto:  4
auto:  4
auto:  4
auto:  4
auto:  4
[2 2]
2.23606797749979 2.23606797749979
0.6435011087932847
