# Numpy Operations

NumPy is the foundation of the Python machine learning stack. NumPy allows for efficient operations on the data structures often used in machine learning: vectors, matrices, and tensors. 

For More visit  **[This Link](https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html)**

In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse

## Creating a Vector
NumPy’s main data structure is the multidimensional array. To create a vector, we simply create a one-dimensional array. Just like vectors, these arrays can be represented horizontally (i.e., rows) or vertically (i.e., columns).

In [49]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])
print(vector_row)

# Create a vector as a column
vector_column = np.array([[1],[2],[3]])
print(vector_column)


[1 2 3]
[[1]
 [2]
 [3]]


# Some Basic Operation

In [50]:
array = np.array([1,2,3])
print(array)

# Sqrt
print(np.sqrt(array))

# Exponential
print(np.exp(array))

# log
print(np.log(array))

[1 2 3]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


# Creating Matrix All Zeros/Ones

In [56]:
# One Dimensions
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [61]:
# Two Dimensions
print(np.zeros((10,10)))
print("#################################")
print(np.ones((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
#################################
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Selecting Elements
Like most things in Python, NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1.

In [51]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)

# Select second row, second column
print("second row, second column:",matrix[1,1])

# Select the first two rows and all columns of a matrix
print("first two rows and all columns")
print(matrix[:2,:])

# Select all rows and the second column
print("all rows and the second column")
print(matrix[:,1:2])

# select 1st row
print(matrix[:1,:])

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
second row, second column: 5
first two rows and all columns
[[1 2 3]
 [4 5 6]]
all rows and the second column
[[2]
 [5]
 [8]]
[[1 2 3]]


# Dot Product

In [52]:
A = np.array([1,2])

B = np.array([2,1])

# Find Magnitude Manual Operation
dot = 0
for ai, bi in zip(A,B):
    dot += ai*bi
print("manual: ",dot)

# Automatic Operation
print("auto: ",np.sum(A*B))
print("auto: ",(A*B).sum()) #Similar
print("auto: ",np.dot(A,B)) # similar
print("auto: ", A.dot(B))
print("auto: ", B.dot(A))

# Dot Product
print(A*B)
A_magnitude = np.linalg.norm(A)
B_magnitude = np.linalg.norm(B)
print(A_magnitude, B_magnitude)

# Angel
cosangle = A.dot(B)/(A_magnitude*B_magnitude)
angel = np.arccos(cosangle)
print(angel)


manual:  4
auto:  4
auto:  4
auto:  4
auto:  4
auto:  4
[2 2]
2.23606797749979 2.23606797749979
0.6435011087932847
