# NumPy Basic Operations

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse

# https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html

# Applying Operations to Elements

### NumPy’s vectorize
NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array. It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance

In [32]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

print(vectorized_add_100(matrix))

[[101 102 103]
 [104 105 106]
 [107 108 109]]


NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting). For example, we can create a much simpler version of our solution using broadcasting:

In [33]:
# Add 100 to all elements as before
matrix = matrix + 100
print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


# Maximum and Minimum Value

You need to find the maximum or minimum value in an array.


In [34]:
# Return maximum element
print(np.max(matrix))

# Return minimum element
print(np.min(matrix))



109
101


Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the max and min methods. Using the axis parameter we can also apply the operation along a certain axis:

**axis=0 means column and axis=1 means row**

In [35]:
# Find maximum element in each column
print(np.max(matrix, axis=0))

# Find maximum element in each row
print(np.max(matrix, axis=1))

[107 108 109]
[103 106 109]


# Average, Variance, and Standard Deviation

Use NumPy’s **mean, var, and std**. Just like with max and min, we can easily get descriptive statistics about the whole matrix or do calculations along a single axis.

In [36]:
print(matrix)
# Return mean
print(np.mean(matrix))

# return variance
print(np.var(matrix))

# return standard deviation
print(np.std(matrix))

# Find the mean value in each column
print(np.mean(matrix, axis=0))

[[101 102 103]
 [104 105 106]
 [107 108 109]]
105.0
6.666666666666667
2.581988897471611
[104. 105. 106.]


# Reshaping Arrays

Reshape allows us to restructure an array so that we maintain the same data but it is organized as a different number of rows and columns. The only requirement is that **the shape of the original and new matrix contain the same number of elements (i.e., the same size).**

In [40]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix=matrix.reshape(2, 6)
print(matrix)

# Agein Reshape
matrix=matrix.reshape(4, 3)
print(matrix)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(-1, 1) means one row and as many columns as needed.
Similarly, if we provide one integer, reshape will return a 1D array of that length:

In [51]:
print(matrix.reshape(1, -1))

print(matrix.reshape(12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Flattening a Matrix
flatten is a simple method to transform a matrix into a one-dimensional array. Alternatively, we can use reshape to create a row vector:

In [58]:
print(matrix.flatten()) # flatten
print(matrix.reshape(1, -1)) # row vector

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
