# Numpy Vs List

In [32]:
import numpy as np

# List 
L = [1,2,3]

A = np.array([1,2,3])

# Append Method

In [33]:
# Numpy doesn't support Append Method

L.append(4)
print(L)

try:
    A.append(4)
    print(A)
except Exception as e:
    print(e)

[1, 2, 3, 4]
'numpy.ndarray' object has no attribute 'append'


# Concatetion

In [34]:
# Numpy Doesn't Support List Like Concatenation.
L = L + [5]
print(L)
try:
    A = A + [4,5]
    print(A)
except Exception as e:
    print(e)

[1, 2, 3, 4, 5]
operands could not be broadcast together with shapes (3,) (2,) 


In [35]:
# See Output to know the diffirences

print(L + L)

print(A + A)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2 4 6]


# Multiplication

In [36]:
try:
    A = A + [4,5]
    print(A)
except Exception as e:
    print(e)print(A*2)
print(L*2)

[2 4 6]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# Squaring 

In [39]:
# For Numpy
print(A**2)

# List Doesn't Support This Kinds of operation
try:
    print(L**2)
except Exception as e:
    print(e)
    
# To do so, we have to iterate through the loop
L2 = []
for i in L:
    L2.append(i*i)

print(L2)
    

[1 4 9]
unsupported operand type(s) for ** or pow(): 'list' and 'int'
[1, 4, 9, 16, 25]


# Other Operations

In [42]:
# sqrt
np.sqrt(A)

# Log
np.log(A)

# exponential
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])