# Generating Random Values

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import sparse

NumPy offers a wide variety of means to generate random numbers, many more than can be covered here. In our solution we generated floats; however, it is also common to generate integers

In [4]:
# Set seed
np.random.seed(1)

# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04])

In [10]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([7, 7, 9])

In [11]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([ 0.67723401, -0.10687843,  0.72527406])

In [12]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.8027575 , 1.09280081, 1.51815255])